catalog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', include('triangle.urls'))
]

triangle/urls.py
from django.urls import path

from . import views


app_name = 'triangle'
urlpatterns = [
    path('triangle/', views.triangle, name='triangle'),
    path('person/', views.persons_all, name='persons_all'),
    path('person/create', views.create_person, name='create_person'),
    path('person/<int:pk>', views.update_person, name='update_person'),
]

catalog/models.py
from django.db import models


class City(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Stuff(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Client(models.Model):
    name = models.CharField(max_length=50)
    stuff = models.ManyToManyField(Stuff)
    city = models.ForeignKey(City, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Provider(models.Model):
    name = models.CharField(max_length=50)
    city = models.OneToOneField(City, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

triangle/models.py
from django.db import models


class Person(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)

    def __str__(self):
        return f'{self.first_name} {self.last_name} {self.email}'


class Logs(models.Model):
    CHOICES = (
        ('CONNECT', 'CONNECT'),
        ('DELETE', 'DELETE'),
        ('GET', 'GET'),
        ('HEAD', 'HEAD'),
        ('OPTIONS', 'OPTIONS'),
        ('POST', 'POST'),
        ('PUT', 'PUT'),
    )
    path = models.CharField(max_length=255)
    method = models.CharField(max_length=7, choices=CHOICES)
    timestamp = models.DateTimeField(auto_now_add=True)
    status_code = models.IntegerField()
    data = models.JSONField(blank=True, null=True)

    def __str__(self):
        return f'{self.method} {self.timestamp} {self.data}'

triangle/forms.py
from django import forms

from .models import Person


class Hypotenuse(forms.Form):
    base = forms.IntegerField(label="Length of the triangle's base", help_text='mm', min_value=1)
    altitude = forms.IntegerField(label="Length of the triangle's altitude", help_text='mm', min_value=1)


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ['first_name', 'last_name', 'email']

catalog/views.py
from django.http import HttpResponse


def index(request):
    return HttpResponse("Hello, world. You're at the catalog index.")

triangle/views.py
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PersonForm, Hypotenuse
from .models import Person


def triangle(request):
    hypotenuse = None
    if "OK" in request.GET:
        my_form = Hypotenuse(request.GET)

        if my_form.is_valid():
            base = my_form.cleaned_data['base']
            altitude = my_form.cleaned_data['altitude']
            hypotenuse = round(((base ** 2 + (altitude ** 2)) ** 0.5), 2)

            my_form = Hypotenuse()
    else:
        my_form = Hypotenuse()

    return render(request, 'triangle/triangle.html', {'form': my_form, 'hypotenuse': hypotenuse})


def create_person(request):
    if request.method == 'POST':
        user_form = PersonForm(request.POST)

        if user_form.is_valid():
            user_form.save()
            return redirect('triangle:persons_all')

    else:
        user_form = PersonForm()

    return render(request, 'triangle/create_person.html', {'form': user_form})


def persons_all(request):
    all_persons = Person.objects.all()
    return render(request, 'triangle/all_persons.html', {'users': all_persons})


def update_person(request, pk):
    obj = get_object_or_404(Person, pk=pk)

    if request.method == 'POST':
        user_form = PersonForm(request.POST, instance=obj)

        if user_form.is_valid():
            obj = user_form.save()
            return redirect('triangle:person')

    else:
        user_form = PersonForm(instance=obj)

    return render(request, 'triangle/update_person.html', {'form': user_form, 'obj': obj})

templates/triangle/all_persons.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>All persons</title>
</head>
<body>
    <ul>
    {% for user in users %}
        <li><a href="{% url 'triangle:update_person' pk=user.pk %}">{{ user }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>

templates/triangle/create_person.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create</title>
</head>
<body>
    <h1>Create a person</h1>
    <form action="{% url 'triangle:create_person' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <input type="Submit" name="Submit" value="Submit">
    </form>
</body>
</html>

templates/triangle/triangle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hypotenuse</title>
</head>
<body>
    <h1>Hypotenuse</h1>
    <form action="{% url 'triangle:triangle' %}" method="get">
        <p>{{ form.base.label_tag }} {{ form.base }}</p>
        <p>{{ form.altitude.label_tag }} {{ form.altitude }}</p>
    <input type="Submit" name="OK" value="OK">
    </form>
    {% if hypotenuse %}
        <p>Hypotenuse: {{ hypotenuse }}</p>
    {% endif %}
</body>
</html>

templates/triangle/update_person.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update</title>
</head>
<body>
    <h1>{{ obj }}</h1>
    <form action="{% url 'triangle:update_person' pk=obj.pk %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <input type="Submit" name="Submit" value="Submit">
    </form>
</body>
</html>